### ISSUE TITLE
Fatal error ocurred. See event log for details

### ISSUE THREAD

**Issue by roadsign** [SteamGridDB/steam-rom-manager#183]
Hi,

I was able to generate an app list for the first few times I was playing around with this program, but now it seems stuck. Event log:

```
...
Parser test is completed.
All available image urls retrieved.
Executing parsers.
Please shutdown Steam if it is running.
Fatal error occurred. See event log for details.
TypeError: Cannot read property 'width' of null
```
What I've tried so far:
- Removing `localconfig.vdf` and `shortcuts*.vdf` from all accounts in steam's folder

Info:
- Steam-ROM-Manager-portable-2.2.27-31;
- Steam non-beta;
- Windows 10 x64;
- Emulators: Dolphin and/or Cemu.

**Comment by cbartondock** [comment]
Should be fixed in 2.2.32. Please follow the instructions for the release and confirm.

**Comment by cbartondock** [comment]
Could you try 2.2.33?

**Comment by roadsign** [comment]
It still happens in `SRM version - 2.2.33 Portable`

I also removed folder `leveldb`, per release notes, before testing again.

**Comment by cbartondock** [comment]
Do you have preload images enabled in the settings? If so disable it. I have found the bug and this will be fixed in the next version. Going to post a link to an exe for you to test in like three minutes

**Comment by cbartondock** [comment]
Try this build and let me know if it is fixed: [https://www.dropbox.com/sh/izkrl6mah3lgtz0/AAC6BesVOx6o_O_n8fC92g00a?dl=0](https://www.dropbox.com/sh/izkrl6mah3lgtz0/AAC6BesVOx6o_O_n8fC92g00a?dl=0)

**Comment by roadsign** [comment]
> Do you have preload images enabled in the settings? If so disable it. I have found the bug and this will be fixed in the next version. Going to post a link to an exe for you to test in like three minutes

It wasn't enabled. I let my settings at default:

![image](https://user-images.githubusercontent.com/4549900/83800112-49f2e780-a67d-11ea-89ef-abfd22f1e1d4.png)

> Try this build and let me know if it is fixed: https://www.dropbox.com/sh/izkrl6mah3lgtz0/AAC6BesVOx6o_O_n8fC92g00a?dl=0

That managed to generate the app list!

Now it's throwing an error when saving:

```
...
Parser test is completed.
All available image urls retrieved.
Executing parsers.
Please shutdown Steam if it is running.
All available image urls retrieved.
Populating VDF list.
Creating backups.
Reading VDF files.
Merging VDF entries.
Saving added category information to localconfig.vdf
Error updating categories. See event log for details.
Category error (shortcuts and artwork will still be added): Key not found in database [_https://steamloopback.hostU34771195-cloud-storage-namespaces]
Done adding/removing entries.
Populating VDF list.
Creating backups.
Reading VDF files.
Merging VDF entries.
Saving added category information to localconfig.vdf
Error updating categories. See event log for details.
Category error (shortcuts and artwork will still be added): Key not found in database [_https://steamloopback.hostU34771195-cloud-storage-namespaces]
Done adding/removing entries.
```

**Comment by cbartondock** [comment]
Do you have any categories saved at all? If so could you zip a copy of your leveldb directory and send it to me? (zip it while steam is closed)

**Comment by cbartondock** [comment]
You might also try exiting steam and re-entering it, or restarting the computer. For whatever reason steam isn't regenerating your leveldb properly

**Comment by roadsign** [comment]
I have some categories saved. How can I send the zip?

**Comment by cbartondock** [comment]
Message me on the discord at lontanadascienza
https://discord.gg/r2xHErC

**Comment by cbartondock** [comment]
Closing this as the original issue was resolved in 2.2.34
