### ISSUE TITLE
Games not being grouped into categories

### ISSUE THREAD

**Issue by PoorAndNeedy** [SteamGridDB/steam-rom-manager#205]
When clicking "save app list" the roms are successfully added as shortcuts in steam, but they are not being grouped into collections. I've attempted:

- Restarting computer
- Updating SRM
- Manually removing existing collections
- Manually creating collections to match the names in the parsers
- Opting out of steam beta

Here is my log:

> Populating VDF list.
> Creating backups.
> Reading VDF files.
> Merging VDF entries.
> Saving added category information to localconfig.vdf
> Error updating categories. See event log for details.
> Category error (shortcuts and artwork will still be added): Key not found in database [_https://steamloopback.hostU122415782-cloud-storage-namespaces]
> Done adding/removing entries.

**Comment by thewalkerberry** [comment]
Same

**Comment by cbartondock** [comment]
Most likely steam updated the structure of their files, I will take a look

**Comment by cbartondock** [comment]
It seems to be working fine for me. Could you message me on the discord with a zip of your "C:\Users\YourName\AppData\Local\Steam\htmlcache\Local Storage\leveldb"? **Do not upload it publicly**.

**Comment by PoorAndNeedy** [comment]
I sent a message with the folder to lontanadascienza
#7837

**Comment by kencinder** [comment]
I have to think this is fixed, I've had no problems on the latest release adding numerous parsers with thousands of roms and categories are created just fine.

**Comment by cbartondock** [comment]
Can you try relocating that leveldb file (anywhere), restarting steam to regenerate it, then trying again with srm? So many of these issues are just from some of steam's files having hang overs of older versions.

**Comment by ExpatUK** [comment]
Still getting this issue with the current version - have deleted leveldb and run Steam again to regenerate it, however my categories are still missing.

Here is the event log:

> All available image urls retrieved.
> Executing parsers.
> Please shutdown Steam if it is running.
> All available image urls retrieved.
> Populating VDF list.
> Creating backups.
> Reading VDF files.
> Merging VDF entries.
> Saving added category information to localconfig.vdf
> Error updating categories. See event log for details.
> Category error (shortcuts and artwork will still be added): Key not found in database [_https://steamloopback.hostU118760330-cloud-storage-namespaces]
> Done adding/removing entries.

**Comment by Immersion95** [comment]
This just happened to me, I did that to solve it : 
- Move the steamapps folder elsewhere
- Delete Steam folder in ProgramFiles & Appdata
- Reinstall Steam
- Move back steamapps
- Login
- Use SRM normally

**Comment by ravage007** [comment]
I am now having the same problem and I can't delete my steam and reinstall because it's on my steam deck

**Comment by Ninobrown0615** [comment]
Need help to same issue

**Comment by cbartondock** [comment]
both of you dm me or your leveldb files on discord @lontanadascienza

**Comment by ravage007** [comment]
> both of you dm me or your leveldb files on discord @lontanadascienza

unfortunately I can't I fix the issue but not in the way I recommend I ended up resetting my steam deck to factory settings and just reinstalling everything

**Comment by cbartondock** [comment]
Yeah this does seem like an "outdated steam library" issue. Could possibly be fixed by making sure to specify the user accounts field in SRM, in case SRM is looking at another account by with broken files.

**Comment by cbartondock** [comment]
For future reference, one just needs to set the user accounts filter so that SRM only tries to add games to your account, and not to some broken account that is still on the device.

**Comment by ravage007** [comment]
> For future reference, one just needs to set the user accounts filter so that SRM only tries to add games to your account, and not to some broken account that is still on the device.

thank you so much for adding this

**Comment by DocMAX** [comment]
currently grouping doesn't work again, anyone?

**Comment by mohocklockness** [comment]
I'm having this problem right now, the games are showing up but categories are still not showing up.

**Comment by felipeandreslugosalazar** [comment]
Hi to everyone.
Same problem here.
 The games are showing up but categories are still not showing up.

**Comment by DocMAX** [comment]
Fixed with latest release!

**Comment by benwbooth** [comment]
Fixed in steam or steam-rom-manager?
Are the groups now fixed for libraries greater than 3000 entries?

**Comment by felipeandreslugosalazar** [comment]
@DocMAX 
I factory reset my steamdeck and reinstalled emudeck yesterday and the issue is still there.
I am pretty sure I got the latest versions of steamOS and SMR.
